# Generated by Django 3.2.3 on 2021-05-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
